openapi: "3.0.0"
info:
  title: Brands Service API
  description: This is a brand microservice testing several technologies.
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.1

servers:
  - url: http://localhost/v0.1
    description: Local server

tags:
  - name: brand
    description: Brands endpoints
  - name: category
    description: Categories endpoints

paths:
  /brand:
    get:
      tags:
      - brand
      summary: Returns a list of brands.
      responses:
        '200':
          description: A JSON array of brand objects
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/definitions/Brand'
    post:
      tags:
      - brand
      summary: Add a new brand.
      parameters:  
        - in: body
          name: body
          description: Brand object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Brand'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: 
                $ref: '#/definitions/Brand'
  /brands/{id}:
    put:
      tags:
      - brand
      summary: Add a new brand.
      parameters:
        - in: path
          name: id
          description: The brand's id
          required: true
          schema:
            type: integer
        - in: body
          name: body
          description: Brand object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Brand'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: 
                $ref: '#/definitions/Brand'
        '400':
          description: Invalid id supplied
        '404':
          description: Brand not found
        '405':
          description: Validation exception
    delete:
      tags:
      - brand
      summary: Remove an existent brand.
      parameters:
        - in: path
          name: id
          description: The brand's id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Removed
        '400':
          description: Invalid id supplied
        '404':
          description: Brand not found
        '405':
          description: Validation exception
  /categories:
    get:
      tags:
        - category
      summary: Returns a list of categories.
      responses:
        '200':    # status code
          description: A JSON array of category names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/definitions/Category'
    post:
      tags:
      - category
      summary: Add a new category.
      parameters:  
        - in: body
          name: body
          description: Category object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Category'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: 
                $ref: '#/definitions/Category'
  /categories/{id}:
    put:
      tags:
      - category
      summary: Add a new category.
      parameters:
        - in: path
          name: id
          description: The category's id
          required: true
          schema:
            type: integer
        - in: body
          name: body
          description: Category object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Category'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: 
                $ref: '#/definitions/Category'
        '400':
          description: Invalid id supplied
        '404':
          description: Category not found
        '405':
          description: Validation exception
    delete:
      tags:
      - category
      summary: Remove an existent category.
      parameters:
        - in: path
          name: id
          description: The category's id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Removed
        '400':
          description: Invalid id supplied
        '404':
          description: Category not found
        '405':
          description: Validation exception
definitions:
  Brand:
    type: object
    required:
    - name
      category_id
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
      category_id:
        type: integer
  Category:
    type: object
    required:
    - name
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string